"""add nexus conversations and chat messages

Revision ID: 0dca601975e8
Revises: ea42ca279e73
Create Date: 2026-08-20 17:43:23.103948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dca601975e8'
down_revision: Union[str, Sequence[str], None] = 'ea42ca279e73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nexus_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_intent', sa.String(length=100), nullable=True),
    sa.Column('awaiting', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('pending_user_input', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nexus_conversations_status'), 'nexus_conversations', ['status'], unique=False)
    op.create_index(op.f('ix_nexus_conversations_user_id'), 'nexus_conversations', ['user_id'], unique=False)
    op.create_table('nexus_chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('request_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['nexus_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nexus_chat_messages_conversation_id'), 'nexus_chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_nexus_chat_messages_created_at'), 'nexus_chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_nexus_chat_messages_request_id'), 'nexus_chat_messages', ['request_id'], unique=False)
    op.create_index(op.f('ix_nexus_chat_messages_user_id'), 'nexus_chat_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nexus_chat_messages_user_id'), table_name='nexus_chat_messages')
    op.drop_index(op.f('ix_nexus_chat_messages_request_id'), table_name='nexus_chat_messages')
    op.drop_index(op.f('ix_nexus_chat_messages_created_at'), table_name='nexus_chat_messages')
    op.drop_index(op.f('ix_nexus_chat_messages_conversation_id'), table_name='nexus_chat_messages')
    op.drop_table('nexus_chat_messages')
    op.drop_index(op.f('ix_nexus_conversations_user_id'), table_name='nexus_conversations')
    op.drop_index(op.f('ix_nexus_conversations_status'), table_name='nexus_conversations')
    op.drop_table('nexus_conversations')
    # ### end Alembic commands ###
