"""add password hash to users

Revision ID: e0945d9e3454
Revises: e63c6be49a36
Create Date: 2026-08-13 03:49:46.658153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0945d9e3454'
down_revision: Union[str, Sequence[str], None] = 'e63c6be49a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column("password_hash", sa.String(length=255), nullable=True),
    )

    op.execute(
        "UPDATE users SET password_hash = "
        "'TEMPORARY_DEVELOPMENT_HASH'"
    )

    op.alter_column(
        "users",
        "password_hash",
        existing_type=sa.String(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
